apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "router-config-controller.fullname" . }}-manager-role
  labels:
  {{- include "router-config-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - router.willful.be
  resources:
  - portforwards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - router.willful.be
  resources:
  - portforwards/finalizers
  verbs:
  - update
- apiGroups:
  - router.willful.be
  resources:
  - portforwards/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "router-config-controller.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: router-config-controller
    app.kubernetes.io/part-of: router-config-controller
  {{- include "router-config-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "router-config-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "router-config-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'