apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "router-config-controller.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: router-config-controller
    app.kubernetes.io/part-of: router-config-controller
  {{- include "router-config-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}