name: Release Ingestion Service
on:
  push:
    branches:
      - main
    paths:
      - 'ingestion-service/**/*'
jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          targetPath: ingestion-service
          configFilePath: ingestion-service/GitVersion.yml

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'ingestion-service-${{ steps.gitversion.outputs.semVer }}'
          name: 'ingestion-service-${{ steps.gitversion.outputs.semVer }}'
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker Image
        working-directory: ./ingestion-service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --tag ghcr.io/renato0307/grow-ingestion-service:v${{ steps.gitversion.outputs.semVer }}
          docker push ghcr.io/renato0307/grow-ingestion-service:v${{ steps.gitversion.outputs.semVer }}
